#!/bin/bash

echo "Playing URL" `xsel -o`

STREAM=/tmp/stream.mpg

if [ ! -e "$STREAM" ]; then
    echo "creating stream" $STREAM
    mkfifo $STREAM
fi

youtubecmd="youtube-dl --max-downloads 1 -o - `xsel -o` | buffer -p 75 > $STREAM"

eval "${youtubecmd}" &

sleep 15

omxplayer $STREAM -b

rm "$STREAM"


